language: node_js

os: linux
dist: jammy

git:
  depth: 25

node_js:
  - 18.16.0
before_install:
  - npm install -g npm@latest

#services:
#  - xvfb
#addons:
#  chrome: stable
#  apt:
#    packages:
#      - libgconf-2-4
before_script:
  - export DISPLAY=:99.0
install:
  - npm config set progress true
  - npm install

#cache:
  # cache both npm modules and Cypress binary
#  npm: true
#  directories:
#    - ~/.npm
#    - ~/.cache

script:
  #  - npm run test
  - npm run build

#defaults: &defaults
#  script:
#    #   ## print all Travis environment variables for debugging
#    - $(npm bin)/print-env TRAVIS
#    - npm run build:prod
#    # after all tests finish running we need
#    # to kill all background jobs (like "npm start &")
#    - kill $(jobs -p) || true
