language: node_js
git:
  depth: 1
node_js:
  # Node 10.3+ includes npm@6 which has good "npm ci" command
  - 10.8

addons:
  chrome: stable
  apt:
    packages:
    - libgconf-2-4

cache:
  # cache both npm modules and Cypress binary
  npm: true
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm ci
#    - npm run cy:verify

defaults: &defaults
  script:
    #   ## print all Travis environment variables for debugging
    - $(npm bin)/print-env TRAVIS
    - npm run build:prod
    # after all tests finish running we need
    # to kill all background jobs (like "npm start &")
    - kill $(jobs -p) || true